package com.tam.mybike.ui.theme

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val SIZE_TEXT_X_LARGE = 20.sp
val SIZE_TEXT_LARGE = 17.sp
val SIZE_TEXT_MEDIUM = 15.sp
val SIZE_TEXT_SMALL = 14.sp
val SIZE_TEXT_X_SMALL = 13.sp
val SIZE_TEXT_XX_SMALL = 12.sp

val SIZE_ROUND_DEFAULT = 4.dp
val SIZE_DEFAULT_SWITCH = 42.dp
val SIZE_DEFAULT_SWITCH_TRACK_STROKE = 14.dp
val SIZE_DEFAULT_SWITCH_THUMB = 23.dp
val SIZE_RIDE_ICON = 20.dp
val SIZE_OPTIONS_ITEM_ICON = 13.dp
val WIDTH_PREVIEW = 400.dp
val WIDTH_OPTIONS_ITEM = 95.dp
val WIDTH_FIELD_BORDER = 1.dp
val WIDTH_NUMBER_PICKER = 65.dp
val HEIGHT_OPTIONS_ITEM = 30.dp
val HEIGHT_WRENCH_PROGRESS_INDICATOR = 5.dp
val HEIGHT_INPUT_FIELD = 42.dp
val HEIGHT_REQUIRED_ICON = 18.dp
val HEIGHT_REQUIRED_ALERT = 15.dp
val HEIGHT_DROPDOWN_FIELD_ITEM = 40.dp
const val SCALE_WAVE_BACKGROUND = 1.2f

val PADDING_XX_SMALL = 2.dp
val PADDING_X_SMALL = 5.dp
val PADDING_SMALL = 11.dp
val PADDING_MEDIUM = 16.dp
val PADDING_LARGE = 21.dp
val PADDING_X_LARGE = 25.dp
val PADDING_XX_LARGE = 30.dp
val PADDING_RIDE_ICON_INSIDE_BACKGROUND = 1.6.dp
val PADDING_RIDE_ICON_IMAGE = 1.dp
val PADDING_OPTIONS_ITEM_END = 0.dp
val PADDING_HORIZONTAL_PROGRESS_INDICATOR = 10.dp
val PADDING_DROPDOWN_CHOICE_END = 0.dp
val OFFSET_X_OPTIONS_MENU = 0.dp
val OFFSET_Y_OPTIONS_MENU = 2.dp
val OFFSET_X_OPTIONS_ITEM_TEXT_TOWARDS_ICON = (-17).dp
val OFFSET_Y_REQUIRED_ICON = (-1).dp
val OFFSET_X_DROPDOWN_FIELD_MENU = 0.dp
val OFFSET_Y_DROPDOWN_FIELD_MENU = (-12).dp
val OFFSET_Y_DROPDOWN_ICON = 2.dp
const val OFFSET_X_WRENCH_STARTING_FROM = 3.5
const val OFFSET_X_WAVE_COLUMN_BEHIND_RECT = 0f
const val OFFSET_Y_WAVE_COLUMN_BEHIND_RECT = 700f

const val WEIGHT_FILL = 1f
const val FACTOR_DISABLED_BUTTON_DARKNESS = 0.66f
const val FACTOR_SELECTED_DROPDOWN_CHOICE_DARKNESS = 0.8f
// We need to overshoot because since material 3, boxes inside an icon toggle button don't align correctly
const val BIAS_SWITCH_THUMB_FULL_RIGHT = 1.3f
const val BIAS_SWITCH_THUMB_FULL_LEFT = -1f
const val BREAKPOINT_BOLT_WARNING_COLOR = 0.99999f
const val FALLBACK_BIKE_PROGRESS = 0f