package com.tam.mybike.ui.theme

const val TEXT_ADD = "Add"
const val TEXT_BIKE = "Bike"
const val TEXT_RIDE = "Ride"
const val TEXT_ADD_BIKE = "$TEXT_ADD $TEXT_BIKE"
const val TEXT_ADD_RIDE = "$TEXT_ADD $TEXT_RIDE"
const val TEXT_CLOSE = "Close"
const val TEXT_CONNECTOR_DEFAULT = ":"
const val TEXT_CONNECTOR_IN = " in"
const val TEXT_SERVICE = "Service"
const val TEXT_DISTANCE = "Distance"
const val TEXT_DURATION = "Duration"
const val TEXT_DATE = "Date"
const val TEXT_EDIT = "Edit"
const val TEXT_DELETE = "Delete"
const val TEXT_OPTIONS = "More options"
const val TEXT_DELETE_PROMPT = "will be deleted."
const val TEXT_CANCEL = "Cancel"
const val TEXT_WRENCH_PROGRESS = "Distance rode on the bike before service is due."
const val TEXT_REQUIRED_FIELD_CONTENT = "This field is required"
const val TEXT_REQUIRED_FIELD = "Required field"
const val TEXT_OK = "Ok"
const val TEXT_HOURS_MINUTES_DIVIDER = ":"
const val TEXT_HOURS = "Hours"
const val TEXT_MINUTES = "Minutes"
const val TEXT_DURATION_DESCRIPTION_HOURS = "h, "
const val TEXT_DURATION_DESCRIPTION_MINUTES = "min"
const val TEXT_EXTEND_FIELD_CHOICES = "Extend to select from choices for this field"
const val TEXT_UNDER_BIKE_CONTENT = "The wheels of the bike."
const val TEXT_MIDDLE_BIKE_CONTENT = "The bike frame."
const val TEXT_OVER_BIKE_CONTENT = "The bike's seat, handle and paddles"
const val TEXT_BIKES = "Bikes"
const val TEXT_WHEELS = "Wheels"
const val TEXT_INCHES_NOTATION = "\""
const val TEXT_KM_UNIT = "km"
const val TEXT_MI_UNIT = "mi"
const val TEXT_MISSING_BIKES_CONTENT = "No bikes have been added."
const val TEXT_MISSING_BIKES_DOTTED_LINE_CONTENT = "Proceed to adding a bike."
const val TEXT_MISSING_BIKES = "You don't have any bike added yet.\n" +
    "Add you first bike and start registering\n" +
    "your rides in order to keep your bike\n" +
    "service cycles up to date."
const val TEXT_MISSING_RIDES_CONTENT = "No rides have been added."
const val TEXT_MISSING_RIDES_DOTTED_LINE_CONTENT = "Proceed to adding a ride."
const val TEXT_RIDES = "Rides"
const val TEXT_STATISTICS_ICON_CONTENT = "Statistics icon"
const val TEXT_STATISTICS_TITLE = "All Rides Statistics"
const val TEXT_TOTAL = "Total: "
const val TEXT_ROAD = "Road"
const val TEXT_MTB = "MTB"
const val TEXT_CITY = "City"
const val TEXT_EBIKE = "E-Bike"
const val TEXT_OLDER = "OLDER"

const val PATTERN_DATE = "dd.MM.uuuu"
const val PATTERN_NUMBER = "#,###"
const val PATTERN_NUMBER_TO_REPLACE = ','
const val PATTERN_NUMBER_REPLACE_WITH = '.'