package com.tam.mybike.ui.theme

const val TEXT_ADD = "Add"
const val TEXT_BIKE = "Bike"
const val TEXT_RIDE = "Ride"
const val TEXT_ADD_BIKE = "$TEXT_ADD $TEXT_BIKE"
const val TEXT_ADD_RIDE = "$TEXT_ADD $TEXT_RIDE"
const val TEXT_CLOSE = "Close"
const val TEXT_CONNECTOR_DEFAULT = ":"
const val TEXT_CONNECTOR_IN = " in"
const val TEXT_SERVICE = "Service"
const val TEXT_DISTANCE = "Distance"
const val TEXT_DURATION = "Duration"
const val TEXT_DATE = "Date"
const val TEXT_EDIT = "Edit"
const val TEXT_DELETE = "Delete"
const val TEXT_OPTIONS = "More options"
const val TEXT_DELETE_PROMPT = "will be deleted."
const val TEXT_CANCEL = "Cancel"
const val TEXT_WRENCH_PROGRESS = "Distance rode on the bike before service is due."
const val TEXT_REQUIRED_FIELD_CONTENT = "This field is required"
const val TEXT_REQUIRED_FIELD = "Required field"
const val TEXT_OK = "Ok"
const val TEXT_HOURS_MINUTES_DIVIDER = ":"
const val TEXT_HOURS = "Hours"
const val TEXT_MINUTES = "Minutes"
const val TEXT_DURATION_DESCRIPTION_HOURS = "h, "
const val TEXT_DURATION_DESCRIPTION_MINUTES = "min"
const val TEXT_EXTEND_FIELD_CHOICES = "Extend to select from choices for this field"

const val PATTERN_DATE = "dd.MM.uuuu"